SELECT * FROM TMP_TRACKGLRESBUILT ORDER BY SR_NO DESC; -- tracking table for the script completion
/
SELECT * from
(
SELECT
--*
PERIOD_CODE
,ROUND(sum(decode(CATEGORY ,'1',1,1) * (DR_BAL_LCY)),0) DR_BAL_LCY
,ROUND(sum(decode(CATEGORY ,'1',1,1) * (CR_BAL_LCY)),0) CR_BAL_LCY
FROM GLTB_GL_BAL_ALL a
WHERE FIN_YEAR = 'FY2022'
--AND PERIOD_CODE = 'M06'
AND BRANCH_CODE = '000'
AND LEAF = 'Y'
AND CATEGORY IN ('1','2','3','4')
AND NOT (CATEGORY IN ('3','4') AND CCY_CODE !='IDR')
GROUP BY PERIOD_CODE--,CATEGORY
);
/

