--CHECK IMBALANCE
SELECT FIN_YEAR, PERIOD_CODE, DR_BAL_LCY, CR_BAL_LCY, (CR_BAL_LCY-DR_BAL_LCY) Diff from
(
SELECT
--*
FIN_YEAR,
PERIOD_CODE
,ROUND(sum(decode(CATEGORY ,'1',1,1) * (DR_BAL_LCY)),0) DR_BAL_LCY
,ROUND(sum(decode(CATEGORY ,'1',1,1) * (CR_BAL_LCY)),0) CR_BAL_LCY
FROM GLTB_GL_BAL a
WHERE FIN_YEAR in ('FY2022','FY2023')
--AND PERIOD_CODE = 'M06'
AND BRANCH_CODE = '000'
AND LEAF = 'Y'
AND CATEGORY IN ('1','2','3','4')
AND NOT (CATEGORY IN ('3','4') AND CCY_CODE !='IDR')
GROUP BY FIN_YEAR, PERIOD_CODE order by PERIOD_CODE
) order by 1
